name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Add MSYS64 bin to PATH
        run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore and build (publish)
        run: msbuild plugin_KinectOne /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:Publish /p:PublishProfile=plugin_KinectOne\Properties\PublishProfiles\FolderProfile.pubxml
        
      - name: Pack published files
        run: |
          cd plugin_KinectOne/bin/Release/net7.0/win10-x64/publish
          7z a plugin_KinectOne.zip *
        
      - name: Upload plugin artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "plugin_KinectOne Build Artifact"
          files: |
            ./plugin_KinectOne/bin/Release/net7.0/win10-x64/publish/plugin_KinectOne.zip
            ./external/manifest.json